name: autorl
channels:
  - conda-forge
  - hcc
  - defaults
dependencies:
  - _anaconda_depends=2022.05=py39_0
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohttp=3.8.3=py39h5eee18b_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py39_1
  - anaconda-client=1.11.0=py39h06a4308_0
  - anaconda-project=0.11.1=py39h06a4308_0
  - anyio=3.5.0=py39h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - arrow=1.2.3=py39h06a4308_0
  - astroid=2.11.7=py39h06a4308_0
  - astropy=5.1=py39h7deecbd_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py39h06a4308_0
  - atomicwrites=1.4.0=py_0
  - attrs=22.1.0=py39h06a4308_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - babel=2.11.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py39h5eee18b_1
  - beautifulsoup4=4.11.1=py39h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bitarray=2.5.1=py39h5eee18b_0
  - bkcharts=0.2=py39h06a4308_1
  - black=22.6.0=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h4ff587b_1
  - bokeh=2.4.3=py39h06a4308_0
  - boto3=1.24.28=py39h06a4308_0
  - botocore=1.27.59=py39h06a4308_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - cfitsio=3.470=hf0d0db6_6
  - chardet=4.0.0=py39h06a4308_1003
  - charls=2.2.0=h2531618_0
  - click=8.0.4=py39h06a4308_0
  - clyent=1.2.2=py39h06a4308_1
  - cmake=3.22.1=h1fce559_0
  - colorama=0.4.6=py39h06a4308_0
  - colorcet=3.0.1=py39h06a4308_0
  - conda=22.11.1=py39h06a4308_4
  - conda-content-trust=0.1.3=py39h06a4308_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=2.0.2=py39h06a4308_0
  - conda-package-streaming=0.7.0=py39h06a4308_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - constantly=15.1.0=pyh2b92418_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=38.0.4=py39h9ce1e76_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - cudatoolkit=11.4.4=h5e1937b_3
  - cudnn=8.1.0.77=h90431f1_0
  - curl=7.86.0=h5eee18b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.32=py39h6a678d5_0
  - cytoolz=0.12.0=py39h5eee18b_0
  - daal4py=2021.6.0=py39h79cecc1_1
  - dal=2021.6.0=hdb19cb5_916
  - dask-core=2022.2.1=pyhd3eb1b0_0
  - datashader=0.14.3=py39h06a4308_0
  - datashape=0.5.4=py39h06a4308_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.6=py39h06a4308_0
  - docutils=0.18.1=py39h06a4308_3
  - entrypoints=0.4=py39h06a4308_0
  - et_xmlfile=1.1.0=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - flake8=4.0.1=pyhd3eb1b0_1
  - flask=2.2.2=py39h06a4308_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h52c9d5c_1
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py39h5eee18b_0
  - future=0.18.2=py39h06a4308_1
  - gensim=4.1.2=py39h295c915_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - google-api-core=2.10.1=py39h06a4308_0
  - google-cloud-core=2.3.2=py39h06a4308_0
  - google-cloud-storage=2.6.0=py39h06a4308_0
  - google-crc32c=1.5.0=py39h5eee18b_0
  - google-resumable-media=2.4.0=py39h06a4308_0
  - googleapis-common-protos=1.56.4=py39h06a4308_0
  - greenlet=2.0.1=py39h6a678d5_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf5=1.10.6=hb1b8bf9_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.15.3=py39h06a4308_0
  - hvplot=0.8.2=py39h06a4308_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - imagecodecs=2021.8.26=py39hf0132c2_1
  - imagesize=1.4.1=py39h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py39h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.6=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.17.1=pyh210e3f2_0
  - ipython=7.31.1=py39h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jellyfish=0.9.0=py39h7f8727e_0
  - jinja2=3.1.2=py39h06a4308_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jq=1.6=h27cfd23_1000
  - json5=0.9.6=pyhd3eb1b0_0
  - jupyter=1.0.0=py39h06a4308_8
  - jupyter_client=7.4.8=py39h06a4308_0
  - jupyter_console=6.4.4=py39h06a4308_0
  - jupyter_core=5.1.1=py39h06a4308_0
  - jupyter_server=1.23.4=py39h06a4308_0
  - jupyterlab=3.5.2=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.16.5=py39h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - keyring=23.4.0=py39h06a4308_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.19.2=hac12032_0
  - lazy-object-proxy=1.6.0=py39h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libarchive=3.6.1=hab531cd_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcrc32c=1.1.2=h6a678d5_0
  - libcurl=7.86.0=h91b91d3_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - liblief=0.12.3=h6a678d5_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=h9e868ea_6
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.20.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzopfli=1.0.3=he6710b0_0
  - llvmlite=0.39.1=py39he621ea3_0
  - locket=1.0.0=py39h06a4308_0
  - lxml=4.9.1=py39h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - lzo=2.10=h7b6447c_2
  - markdown=3.4.1=py39h06a4308_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mock=4.0.3=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpi=1.0=mpich
  - mpich=3.3.2=hc856adb_0
  - mpmath=1.2.1=py39h06a4308_0
  - msgpack-python=1.0.3=py39hd09550d_0
  - multidict=6.0.2=py39h5eee18b_0
  - multipledispatch=0.6.0=py39h06a4308_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py39h06a4308_1
  - nbclassic=0.4.8=py39h06a4308_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.5.4=py39h06a4308_0
  - nbformat=5.7.0=py39h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.6=py39h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nltk=3.7=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.5.2=py39h06a4308_0
  - notebook-shim=0.2.2=py39h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numba=0.56.4=py39h417a72b_0
  - numexpr=2.8.4=py39he184ba9_0
  - numpy-base=1.21.5=py39ha15fc14_3
  - numpydoc=1.5.0=py39h06a4308_0
  - nvcc_linux-64=10.1=hcaf9a05_10
  - olefile=0.46=pyhd3eb1b0_0
  - oniguruma=6.9.7.1=h27cfd23_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.0.10=py39h5eee18b_0
  - openssl=1.1.1s=h7f8727e_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.14.1=py39h06a4308_0
  - param=1.12.3=py39h06a4308_0
  - parsel=1.6.0=py39h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patchelf=0.15.0=h6a678d5_0
  - pathspec=0.9.0=py39h06a4308_0
  - pcre=8.45=h295c915_0
  - pep8=1.7.1=py39h06a4308_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pkginfo=1.8.3=py39h06a4308_0
  - plotly=5.9.0=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - ply=3.11=py39h06a4308_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protego=0.1.16=py_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - py-lief=0.12.3=py39h6a678d5_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycosat=0.6.4=py39h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.4.8=py39h06a4308_1
  - pycurl=7.45.1=py39h8f2d780_0
  - pydispatcher=2.0.5=py39h06a4308_2
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyerfa=2.0.0=py39h27cfd23_0
  - pyflakes=2.4.0=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyhamcrest=2.0.2=pyhd3eb1b0_2
  - pylint=2.14.5=py39h06a4308_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyodbc=4.0.34=py39h6a678d5_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyqtwebengine=5.15.7=py39h6a678d5_1
  - pysocks=1.7.1=py39h06a4308_0
  - pytables=3.7.0=py39hf19a122_1
  - pytest=7.1.2=py39h06a4308_0
  - python=3.9.13=haa1d7c7_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lsp-black=1.2.1=py39h06a4308_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.5.0=py39h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.1=py39h6a678d5_0
  - pytorch=1.12.1=cpu_py39he8d8e81_0
  - pyviz_comms=2.0.2=pyhd3eb1b0_0
  - pywavelets=1.4.1=py39h5eee18b_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0=py39h5eee18b_1
  - pyzmq=23.2.0=py39h6a678d5_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.15.9=h06a4308_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.2=py39h06a4308_0
  - qtpy=2.2.0=py39h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - queuelib=1.5.0=py39h06a4308_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - rhash=1.4.1=h3c74f83_1
  - ripgrep=13.0.0=hbdeaff8_0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py39h06a4308_1
  - ruamel.yaml=0.17.21=py39h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py39h5eee18b_1
  - ruamel_yaml=0.17.21=py39h5eee18b_0
  - s3transfer=0.6.0=py39h06a4308_0
  - scikit-image=0.19.3=py39h6a678d5_1
  - scikit-learn-intelex=2021.6.0=py39h06a4308_0
  - scrapy=2.6.2=py39h06a4308_0
  - seaborn=0.12.2=py39h06a4308_0
  - secretstorage=3.3.1=py39h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - sip=6.6.2=py39h6a678d5_0
  - smart_open=5.2.1=py39h06a4308_0
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py39h06a4308_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.2.post1=py39h06a4308_0
  - sphinx=5.0.2=py39h06a4308_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.3.3=py39h06a4308_0
  - spyder-kernels=2.3.3=py39h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.11.1=py39h06a4308_0
  - tbb=2021.6.0=hdb19cb5_1
  - tbb4py=2021.6.0=py39hdb19cb5_1
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.0.1=py39h06a4308_1
  - terminado=0.17.1=py39h06a4308_0
  - testpath=0.6.0=py39h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss=0.4=pyhd3eb1b0_1002
  - tinycss2=1.2.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tldextract=3.2.0=pyhd3eb1b0_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - tomlkit=0.11.1=py39h06a4308_0
  - toolz=0.12.0=py39h06a4308_0
  - tornado=6.2=py39h5eee18b_0
  - traitlets=5.7.1=py39h06a4308_0
  - twisted=22.2.0=py39h5eee18b_1
  - typed-ast=1.4.3=py39h7f8727e_1
  - typing-extensions=4.4.0=py39h06a4308_0
  - typing_extensions=4.4.0=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - ujson=5.4.0=py39h6a678d5_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - unixodbc=2.3.11=h5eee18b_0
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=0.58.0=py39h06a4308_4
  - werkzeug=2.2.2=py39h06a4308_0
  - wget=1.21.3=h0b77cf5_0
  - whatthepatch=1.0.2=py39h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - wurlitzer=3.0.2=py39h06a4308_0
  - xarray=2022.11.0=py39h06a4308_0
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.3=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.8.1=py39h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zlib=1.2.13=h5eee18b_0
  - zope=1.0=py39h06a4308_1
  - zope.interface=5.4.0=py39h7f8727e_0
  - zstandard=0.18.0=py39h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==0.15.0
    - aiosignal==1.3.1
    - ale-py==0.7.4
    - alembic==1.9.1
    - antlr4-python3-runtime==4.9.3
    - astunparse==1.6.3
    - autopage==0.5.1
    - autorl-sweepers==0
    - autorom==0.4.2
    - autorom-accept-rom-license==0.4.2
    - baselines==0.1.6
    - bayesian-optimization==1.4.2
    - brax==0.0.10
    - cachetools==5.2.0
    - cfgv==3.3.1
    - charset-normalizer==2.1.1
    - chex==0.1.5
    - clang==5.0
    - cliff==4.1.0
    - cloudpickle==2.2.0
    - cma==3.0.3
    - cmaes==0.9.1
    - cmd2==2.4.2
    - colorlog==6.7.0
    - commonmark==0.9.1
    - configspace==0.6.0
    - contourpy==1.0.7
    - coolname==2.2.0
    - dask==2022.9.1
    - dataclasses==0.6
    - dehb==0.0.4
    - distlib==0.3.6
    - distributed==2022.9.1
    - distro==1.8.0
    - dm-env==1.5
    - dm-tree==0.1.7
    - docker-pycreds==0.4.0
    - einops==0.6.0
    - emcee==3.1.2
    - etils==0.9.0
    - ez-setup==0.9
    - fasteners==0.18
    - filelock==3.8.0
    - flake8-bugbear==23.1.14
    - flatbuffers==1.12
    - flax==0.6.1
    - fonttools==4.38.0
    - fsspec==2022.8.2
    - gast==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.29
    - glcontext==2.3.6
    - glfw==1.12.0
    - gnuplotlib==0.38
    - google-auth==2.13.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - gpy==1.10.0
    - gpytorch==1.9.0
    - grpcio==1.49.1
    - gym==0.15.7
    - gym-minigrid==1.1.0
    - gym-notices==0.0.8
    - gym3==0.3.3
    - gymnasium-notices==0.0.1
    - h5py==3.1.0
    - hackrl==0.1.20230117.114312
    - hydra-colorlog==1.2.0
    - hydra-core==1.2.0
    - hydra-nevergrad-sweeper==1.2.0
    - hydra-optuna-sweeper==1.2.0
    - hydra-smac-sweeper==0.0.1
    - hydra-submitit-launcher==1.2.0
    - identify==2.5.13
    - imageio==2.22.2
    - imageio-ffmpeg==0.3.0
    - importlib-metadata==4.13.0
    - importlib-resources==5.10.0
    - jax==0.4.1
    - jaxlib==0.4.1+cuda11.cudnn86
    - jedi==0.18.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - linear-operator==0.1.1
    - lockfile==0.12.2
    - loguru==0.6.0
    - lz4==4.0.0
    - mako==1.2.4
    - matplotlib==3.6.3
    - mccabe==0.6.1
    - memory-profiler==0.61.0
    - moderngl==5.6.4
    - moolib==0.2.0
    - msgpack==1.0.4
    - msgpack-numpy==0.4.8
    - mujoco-py==2.1.2.14
    - networkx==2.8.8
    - nevergrad==0.4.3.post9
    - nle==0.9.0+4f5b57e
    - nodeenv==1.7.0
    - numpy==1.22.0
    - numpysane==0.35
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - omegaconf==2.2.3
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - optax==0.1.3
    - optuna==2.10.1
    - packaging==23.0
    - pandas==1.4.4
    - paramz==0.9.5
    - partd==1.3.0
    - pathtools==0.1.2
    - patsy==0.5.3
    - pbr==5.11.1
    - pillow==9.4.0
    - pip==22.3.1
    - platformdirs==2.5.4
    - pre-commit==2.21.0
    - prettytable==3.6.0
    - procgen==0.10.7
    - promise==2.3
    - protobuf==3.19.6
    - psutil==5.9.2
    - pyasn1-modules==0.2.8
    - pybind11==2.10.3
    - pygame==2.1.2
    - pynisher==0.6.4
    - pyperclip==1.8.2
    - pyrfr==0.8.3
    - pyrsistent==0.19.2
    - pytinyrenderer==0.0.13
    - pytz==2022.2.1
    - ray==2.1.0
    - regex==2022.9.13
    - requests-oauthlib==1.3.1
    - rich==12.5.1
    - rsa==4.9
    - scikit-build==0.16.4
    - scikit-learn==1.1.0
    - scipy==1.9.1
    - sentry-sdk==1.11.0
    - setproctitle==1.3.2
    - setuptools==66.0.0
    - setuptools-scm==7.1.0
    - shortuuid==1.0.11
    - six==1.15.0
    - sklearn==0.0.post1
    - smac==1.4.0
    - smmap==5.0.0
    - sobol-seq==0.2.0
    - sqlalchemy==1.4.46
    - stable-baselines3==1.6.2
    - statsmodels==0.13.5
    - stevedore==4.1.1
    - submitit==1.4.5
    - tabulate==0.9.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tensorflow==2.6.0
    - tensorflow-estimator==2.10.0
    - tensorflow-gpu==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - tensorforce==0.6.5
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - torch==1.12.1+cu113
    - torchaudio==0.12.1+cu113
    - torchvision==0.13.1+cu113
    - tqdm==4.64.1
    - trimesh==3.16.1
    - urllib3==1.26.12
    - virtualenv==20.17.0
    - wandb==0.13.5
    - wrapt==1.12.1
    - zict==2.2.0
    - zipp==3.9.0
prefix: /private/home/theeimer/anaconda3/envs/autorl
